name:                hilbert
version:             0.1.6.0
synopsis:            Number theory in pure Haskell
github:              "pgujjula/hilbert"
license:             GPL-3
author:              "Preetham Gujjula"
maintainer:          "pgujjula+hilbert@protonmail.com"
copyright:           "2020 Preetham Gujjula"

category: Math
description: Please see the README on GitHub at <https://github.com/pgujjula/hilbert#readme>

extra-source-files:
- README.md

dependencies:
- base >= 4.13 && < 5.0

library:
  source-dirs: src
  exposed-modules:
    - Math.NumberTheory.ContinuedFraction
    - Math.NumberTheory.Power
    - Math.NumberTheory.Digit
    - Math.NumberTheory.Diophantine
    - Math.NumberTheory.Modular
    - Math.Combinatorics
    - Math.NumberTheory.Prime
    - Math.Probability
#    - Hilbert.ContinuedFraction
#    - Hilbert.Digit
#    - Hilbert.Legendre
#    - Hilbert.List
#    - Hilbert.Modular
#    - Hilbert.Pell
#    - Hilbert.Prime
#    - Hilbert.Prime.Check.Probable.MillerRabin
#    - Hilbert.Prime.Check.TrialDivision
#    - Hilbert.Prime.Factor.List
#    - Hilbert.Prime.Factor.TrialDivision
#    - Hilbert.Prime.List.Erastosthenes
#    - Hilbert.PriorityQueue
#    - Hilbert.Sequence
#    - Hilbert.Square
#  other-modules:
    - Math.NumberTheory.ContinuedFraction.Core
    - Math.NumberTheory.ContinuedFraction.Sqrt
#    - Hilbert.Prime.Factor.Type
#    - Hilbert.Prime.Factor.List.Lazy
#    - Hilbert.Prime.Factor.List.Strict
#    - Hilbert.Prime.List.Erastosthenes.Lazy
#    - Hilbert.Prime.List.Erastosthenes.Strict
#    - Hilbert.PriorityQueue.ADT
#    - Hilbert.PriorityQueue.Map
#    - Hilbert.PriorityQueue.List
  dependencies:
    - data-ordlist
    - chimera
    - containers
#    - base
#    - mtl
#    - array
#    - pqueue

tests:
  spec:
    source-dirs: test
    main: Main.hs
    other-modules:
      - Math.NumberTheory.ContinuedFraction.CoreSpec
      - Math.NumberTheory.ContinuedFraction.SqrtSpec
      - Math.NumberTheory.DigitSpec
      - Math.NumberTheory.DiophantineSpec
      - Math.NumberTheory.PowerSpec
      - Math.NumberTheory.PrimeSpec
      - Math.NumberTheory.ModularSpec
      - Math.CombinatoricsSpec
      - Spec
#      - Hilbert.ContinuedFraction.SqrtSpec
#      - Hilbert.DigitSpec
#      - Hilbert.ListSpec
#      - Hilbert.LegendreSpec
#      - Hilbert.ModularSpec
#      - Hilbert.PellSpec
#      - Hilbert.Prime.Check.Probable.MillerRabinSpec
#      - Hilbert.Prime.Check.TrialDivisionSpec
#      - Hilbert.Prime.Factor.List.LazySpec
#      - Hilbert.Prime.Factor.List.StrictSpec
#      - Hilbert.Prime.Factor.TrialDivisionSpec
#      - Hilbert.Prime.List.Erastosthenes.LazySpec
#      - Hilbert.Prime.List.Erastosthenes.StrictSpec
#      - Hilbert.PriorityQueue.MapSpec
#      - Hilbert.PriorityQueueTest
    dependencies:
      - hilbert
      - hspec
      - QuickCheck
      - quickcheck-assertions
      - random
      - HUnit
#      - containers
#      - hspec-contrib
#      - random
#      - HUnit
#      - mtl
#      - array
