name:                hilbert
version:             0.1.12.0
synopsis:            Number theory in pure Haskell
github:              "pgujjula/hilbert"
license:             GPL-3
author:              "Preetham Gujjula"
maintainer:          "pgujjula+hilbert@protonmail.com"
copyright:           "2020 Preetham Gujjula"

category: Math
description: Please see the README on GitHub at <https://github.com/pgujjula/hilbert#readme>

extra-source-files:
- README.md

ghc-options:
- -Wall
- -Wcompat
- -Wmissing-export-lists
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wpartial-fields
- -Wmissing-home-modules
- -Werror=missing-home-modules
- -Widentities
- -Wredundant-constraints
- -Wmissing-export-lists

dependencies:
- base >= 4.13 && < 5.0

library:
  source-dirs: src
  exposed-modules:
    - Math.Combinatorics.Binomial
    - Math.Combinatorics.Partition
    - Math.NumberTheory.ContinuedFraction
    - Math.NumberTheory.Digit
    - Math.NumberTheory.Diophantine
    - Math.NumberTheory.Divisor
    - Math.NumberTheory.Fibonacci
    - Math.NumberTheory.Modular
    - Math.NumberTheory.Power
    - Math.NumberTheory.Prime
    - Math.NumberTheory.Prime.Factor
    - Math.Polynomial
    - Math.Probability
#    - Hilbert.Legendre
  other-modules:
    - Math.NumberTheory.ContinuedFraction.Core
    - Math.NumberTheory.ContinuedFraction.Sqrt
  dependencies:
    - data-ordlist
    - chimera
    - containers
    - vector
    - list-duplicate
    - integer-gmp
    - ghc-prim
    - composition

tests:
  spec:
    source-dirs: test
    main: Main.hs
    other-modules:
      - Math.Combinatorics.BinomialSpec
      - Math.Combinatorics.PartitionSpec
      - Math.NumberTheory.ContinuedFraction.CoreSpec
      - Math.NumberTheory.ContinuedFraction.SqrtSpec
      - Math.NumberTheory.DigitSpec
      - Math.NumberTheory.DiophantineSpec
      - Math.NumberTheory.DivisorSpec
      - Math.NumberTheory.FibonacciSpec
      - Math.NumberTheory.ModularSpec
      - Math.NumberTheory.PowerSpec
      - Math.NumberTheory.PrimeSpec
      - Spec
    dependencies:
      - hilbert
      - hspec
      - QuickCheck
      - quickcheck-assertions
      - random
      - HUnit
    ghc-options:
      - -Wno-type-defaults
