name:        hilbert
version:     0.1.21.1
synopsis:    Mathematics in Haskell
github:      "pgujjula/hilbert"
license:     BSD-3-Clause
author:      "Preetham Gujjula"
maintainer:  "libraries@mail.preetham.io"
copyright:   "2023 Preetham Gujjula"
category:    Math
description: Please see the README on GitHub at
             <https://github.com/pgujjula/hilbert#readme>
language: GHC2021

extra-source-files:
- README.md

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Werror=missing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages

dependencies:
- base >= 4.13 && < 5.0

library:
  source-dirs: src
  c-sources: 
  - cbits/num_sum_of_squares_le.c
  cc-options: "-O3"
  exposed-modules:
  - Math.Combinatorics.Binomial
  - Math.Combinatorics.Partition
  - Math.NumberTheory.ContinuedFraction
  - Math.NumberTheory.Digit
  - Math.NumberTheory.Diophantine
  - Math.NumberTheory.Divisor
  - Math.NumberTheory.Fibonacci
  - Math.NumberTheory.Figurate
  - Math.NumberTheory.Gaussian.Divisor
  - Math.NumberTheory.Gaussian.Prime
  - Math.NumberTheory.Gaussian.Prime.Factor
  - Math.NumberTheory.Modular
  - Math.NumberTheory.Power
  - Math.NumberTheory.Prime
  - Math.NumberTheory.Prime.Factor
  - Math.NumberTheory.QuadraticExtension
  - Math.NumberTheory.SumOfSquares
  - Math.NumberTheory.SumOfSquares.Internal
  - Math.Probability
  other-modules:
  - Math.NumberTheory.ContinuedFraction.Core
  - Math.NumberTheory.ContinuedFraction.Sqrt
  - Math.NumberTheory.Prime.SegmentedSieve
  dependencies:
  - apply-merge
  - bitvec
  - containers
  - chimera
  - data-ordlist
  - ghc-typelits-knownnat
  - integer-roots
  - list-duplicate
  - mod
  - primesieve
  - semirings
  - type-natural
  - vector

tests:
  hilbert-tests:
    source-dirs: test
    main: Main.hs
    other-modules:
    - Test.Math.Combinatorics.Binomial
    - Test.Math.Combinatorics.Partition
    - Test.Math.NumberTheory.ContinuedFraction.Core
    - Test.Math.NumberTheory.ContinuedFraction.Sqrt
    - Test.Math.NumberTheory.Digit
    - Test.Math.NumberTheory.Diophantine
    - Test.Math.NumberTheory.Divisor
    - Test.Math.NumberTheory.Figurate
    - Test.Math.NumberTheory.Fibonacci
    - Test.Math.NumberTheory.Gaussian.Divisor
    - Test.Math.NumberTheory.Gaussian.Prime
    - Test.Math.NumberTheory.Gaussian.Prime.Factor
    - Test.Math.NumberTheory.Modular
    - Test.Math.NumberTheory.Power
    - Test.Math.NumberTheory.Prime
    - Test.Math.NumberTheory.Prime.Factor
    - Test.Math.NumberTheory.QuadraticExtension
    - Test.Math.NumberTheory.SumOfSquares
    - Test.Math.Probability
    - Test.Util
    dependencies:
    - chimera
    - ghc-typelits-knownnat
    - hilbert
    - HUnit
    - integer-roots
    - list-duplicate
    - mod
    - primesieve
    - QuickCheck
    - random
    - silently
    - tasty
    - tasty-expected-failure
    - tasty-hunit
    - tasty-quickcheck
    - type-natural
    ghc-options:
    - -Wno-type-defaults

benchmarks:
  primecount-bench:
    source-dirs: bench
    main: Main.hs
    other-modules:
    - Bench.Math.NumberTheory.SumOfSquares
    dependencies:
    - hilbert
    - tasty-bench
