name:                hilbert
version:             0.1.0.0
synopsis:            Number theory in pure Haskell
github:              "pgujjula/hilbert"
license:             GPL-3
author:              "Preetham Gujjula"
maintainer:          "preetham.gujjula@gmail.com"
copyright:           "2020 Preetham Gujjula"

category: Math
description: Please see the README on GitHub at <https://github.com/pgujjula/hilbert#readme>

extra-source-files:
- README.md

library:
  source-dirs: src
  exposed-modules:
    - Hilbert.ContinuedFraction
    - Hilbert.Digit
    - Hilbert.Legendre
    - Hilbert.List
    - Hilbert.Modular
    - Hilbert.Pell
    - Hilbert.Prime
    - Hilbert.Prime.Check.Probable.MillerRabin
    - Hilbert.Prime.Check.TrialDivision
    - Hilbert.Prime.Factor.List
    - Hilbert.Prime.Factor.TrialDivision
    - Hilbert.Prime.List.Erastosthenes
    - Hilbert.PriorityQueue
    - Hilbert.Square
  other-modules:
    - Hilbert.ContinuedFraction.Core
    - Hilbert.ContinuedFraction.Sqrt
    - Hilbert.Prime.Factor.Type
    - Hilbert.Prime.Factor.List.Lazy
    - Hilbert.Prime.Factor.List.Strict
    - Hilbert.Prime.List.Erastosthenes.Lazy
    - Hilbert.Prime.List.Erastosthenes.Strict
    - Hilbert.PriorityQueue.ADT
    - Hilbert.PriorityQueue.Map
    - Hilbert.PriorityQueue.List
  dependencies:
    - base
    - containers
    - mtl
    - array
    - pqueue

executables:
  spec:
    source-dirs: test
    main: Main.hs
    other-modules:
      - Hilbert.ContinuedFraction.CoreSpec
      - Hilbert.ContinuedFraction.SqrtSpec
      - Hilbert.DigitSpec
      - Hilbert.ListSpec
      - Hilbert.LegendreSpec
      - Hilbert.ModularSpec
      - Hilbert.PellSpec
      - Hilbert.Prime.Check.Probable.MillerRabinSpec
      - Hilbert.Prime.Check.TrialDivisionSpec
      - Hilbert.Prime.Factor.List.LazySpec
      - Hilbert.Prime.Factor.List.StrictSpec
      - Hilbert.Prime.Factor.TrialDivisionSpec
      - Hilbert.Prime.List.Erastosthenes.LazySpec
      - Hilbert.Prime.List.Erastosthenes.StrictSpec
      - Hilbert.PriorityQueue.MapSpec
      - Hilbert.PriorityQueueTest
      - Hilbert.SquareSpec
      - Spec
    dependencies:
      - base
      - hilbert
      - hspec
      - hspec-contrib
      - QuickCheck
      - containers
      - random
      - HUnit
      - mtl
      - array
