resolver: lts-19.12
packages:
  - .
extra-deps:
  - list-duplicate-0.1.0.0
  - list-filter-0.1.1.0
  - git: https://github.com/pgujjula/apply-merge
    commit: 5c977e0de0d1ef0f757972378b2ee361b623436f
  - git: git@github.com:pgujjula/chimera.git
    commit: 7cba5f970a34483ce66d6b774416c8499feca4a4
  - git: https://github.com/pgujjula/primesieve-haskell.git
    commit: e433c2e8693fc0a35ac65f1a4f2e08a305ce5acf
