resolver: lts-19.6
packages:
  - .
extra-deps:
  - list-duplicate-0.1.0.0
  - list-filter-0.1.1.0
  - git: https://github.com/pgujjula/apply-merge
    commit: 5c977e0de0d1ef0f757972378b2ee361b623436f
  - git: git@github.com:pgujjula/chimera.git
    commit: 7cba5f970a34483ce66d6b774416c8499feca4a4
  - git: https://github.com/pgujjula/primesieve-haskell.git
    commit: 2facb3215b1a277137f83e9cda53cce15855e47f
