resolver: lts-22.11
packages:
  - .
build:
  benchmark-opts:
    benchmark-arguments: "--color always"
  test-arguments:
    additional-args:
    - "--color"
    - "always"
extra-deps:
  - list-duplicate-0.1.0.0
  - list-filter-0.1.1.0
  - chimera-0.4.0.0
  - git: git@github.com:pgujjula/apply-merge.git
    commit: 38d7fd16427585a9a9df110b6dde2a337f7d9708
  - git: https://github.com/pgujjula/primesieve-haskell.git
    commit: 1b6ba0ca663e585d26a2e46eda2a5b573ae1fc58
