# SPDX-FileCopyrightText: Copyright Preetham Gujjula
# SPDX-License-Identifier: BSD-3-Clause
resolver: lts-22.19
packages:
  - .
build:
  benchmark-opts:
    benchmark-arguments: "--color always"
  test-arguments:
    additional-args:
    - "--color"
    - "always"
extra-deps:
  - list-duplicate-0.1.0.0
  - list-filter-0.1.1.0
  - chimera-0.4.1.0
  - github: pgujjula/apply-merge # 0.1.0.0 (Release Candidate 2)
    commit: '78cdf2cbd844a404f2c0db3f557f0d5445bd1e73'
  - github: sighingnow/primesieve-haskell
    commit: c092414001be7cb54c132b8c1e1e96649ea01a95
    subdirs:
    - primesieve
