resolver: lts-22.11
packages:
  - .
build:
  benchmark-opts:
    benchmark-arguments: "--color always"
  test-arguments:
    additional-args:
    - "--color"
    - "always"
extra-deps:
  - list-duplicate-0.1.0.0
  - list-filter-0.1.1.0
  - chimera-0.4.0.0
  - github: pgujjula/apply-merge # 0.1.0.0 (Release Candidate 2)
    commit: '78cdf2cbd844a404f2c0db3f557f0d5445bd1e73'
  - git: https://github.com/pgujjula/primesieve-haskell.git
    commit: 1b6ba0ca663e585d26a2e46eda2a5b573ae1fc58
